package updates

type Message struct {
    Message_id int64 `json:"message_id"`
    Message_thread_id int64 `json:"message_thread_id"`
    From *User `json:"from"`
    Sender_chat *Chat `json:"sender_chat"`
    Sender_boost_count int64 `json:"sender_boost_count"`
    Sender_business_bot *User `json:"sender_business_bot"`
    Date int64 `json:"date"`
    Business_connection_id string `json:"business_connection_id"`
    Chat *Chat `json:"chat"`
    Forward_origin *MessageOrigin `json:"forward_origin"`
    Is_topic_message bool `json:"is_topic_message"`
    Is_automatic_forward bool `json:"is_automatic_forward"`
    Reply_to_message *Message `json:"reply_to_message"`
    External_reply *ExternalReplyInfo `json:"external_reply"`
    Quote *TextQuote `json:"quote"`
    Reply_to_story *Story `json:"reply_to_story"`
    Via_bot *User `json:"via_bot"`
    Edit_date int64 `json:"edit_date"`
    Has_protected_content bool `json:"has_protected_content"`
    Is_from_offline bool `json:"is_from_offline"`
    Media_group_id string `json:"media_group_id"`
    Author_signature string `json:"author_signature"`
    Text string `json:"text"`
    Entities *[]MessageEntity `json:"entities"`
    Link_preview_options *LinkPreviewOptions `json:"link_preview_options"`
    Effect_id string `json:"effect_id"`
    Animation *Animation `json:"animation"`
    Audio *Audio `json:"audio"`
    Document *Document `json:"document"`
    Paid_media *PaidMediaInfo `json:"paid_media"`
    Photo *[]PhotoSize `json:"photo"`
    Sticker *Sticker `json:"sticker"`
    Story *Story `json:"story"`
    Video *Video `json:"video"`
    Video_note *VideoNote `json:"video_note"`
    Voice *Voice `json:"voice"`
    Caption string `json:"caption"`
    Caption_entities *[]MessageEntity `json:"caption_entities"`
    Show_caption_above_media bool `json:"show_caption_above_media"`
    Has_media_spoiler bool `json:"has_media_spoiler"`
    Contact *Contact `json:"contact"`
    Dice *Dice `json:"dice"`
    Game *Game `json:"game"`
    Poll *Poll `json:"poll"`
    Venue *Venue `json:"venue"`
    Location *Location `json:"location"`
    New_chat_members *[]User `json:"new_chat_members"`
    Left_chat_member *User `json:"left_chat_member"`
    New_chat_title string `json:"new_chat_title"`
    New_chat_photo *[]PhotoSize `json:"new_chat_photo"`
    Delete_chat_photo bool `json:"delete_chat_photo"`
    Group_chat_created bool `json:"group_chat_created"`
    Supergroup_chat_created bool `json:"supergroup_chat_created"`
    Channel_chat_created bool `json:"channel_chat_created"`
    Message_auto_delete_timer_changed *MessageAutoDeleteTimerChanged `json:"message_auto_delete_timer_changed"`
    Migrate_to_chat_id int64 `json:"migrate_to_chat_id"`
    Migrate_from_chat_id int64 `json:"migrate_from_chat_id"`
    Pinned_message *MaybeInaccessibleMessage `json:"pinned_message"`
    Invoice *Invoice `json:"invoice"`
    Successful_payment *SuccessfulPayment `json:"successful_payment"`
    Refunded_payment *RefundedPayment `json:"refunded_payment"`
    Users_shared *UsersShared `json:"users_shared"`
    Chat_shared *ChatShared `json:"chat_shared"`
    Connected_website string `json:"connected_website"`
    Write_access_allowed *WriteAccessAllowed `json:"write_access_allowed"`
    Passport_data *PassportData `json:"passport_data"`
    Proximity_alert_triggered *ProximityAlertTriggered `json:"proximity_alert_triggered"`
    Boost_added *ChatBoostAdded `json:"boost_added"`
    Chat_background_set *ChatBackground `json:"chat_background_set"`
    Forum_topic_created *ForumTopicCreated `json:"forum_topic_created"`
    Forum_topic_edited *ForumTopicEdited `json:"forum_topic_edited"`
    Forum_topic_closed *ForumTopicClosed `json:"forum_topic_closed"`
    Forum_topic_reopened *ForumTopicReopened `json:"forum_topic_reopened"`
    General_forum_topic_hidden *GeneralForumTopicHidden `json:"general_forum_topic_hidden"`
    General_forum_topic_unhidden *GeneralForumTopicUnhidden `json:"general_forum_topic_unhidden"`
    Giveaway_created *GiveawayCreated `json:"giveaway_created"`
    Giveaway *Giveaway `json:"giveaway"`
    Giveaway_winners *GiveawayWinners `json:"giveaway_winners"`
    Giveaway_completed *GiveawayCompleted `json:"giveaway_completed"`
    Video_chat_scheduled *VideoChatScheduled `json:"video_chat_scheduled"`
    Video_chat_started *VideoChatStarted `json:"video_chat_started"`
    Video_chat_ended *VideoChatEnded `json:"video_chat_ended"`
    Video_chat_participants_invited *VideoChatParticipantsInvited `json:"video_chat_participants_invited"`
    Web_app_data *WebAppData `json:"web_app_data"`
    Reply_markup *InlineKeyboardMarkup `json:"reply_markup"`
}